export const API_LIMITS = Object.freeze({
  requestTimeoutMs: 12_000,
  retryBaseDelayMs: 250,
  routeCacheMaxEntries: 40,
  routeCacheTtlMs: 3 * 60 * 1000,
  poiCacheMaxEntries: 40,
  poiCacheTtlMs: 10 * 60 * 1000,
  placeDetailsCacheMaxEntries: 40,
  placeDetailsCacheTtlMs: 30 * 60 * 1000,
  autocompleteCacheMaxEntries: 40,
  autocompleteCacheTtlMs: 2 * 60 * 1000,
  autocompleteDebounceMs: 400,
  autocompleteMinimumLength: 3,
  exploreFirstWaveSize: 5,
  exploreMaximumCandidates: 10,
  poiMaximumRoutePoints: 5,
  poiFirstWaveTypesPerProvider: 2,
  poiFallbackTypesPerProvider: 1,
  poiMaximumConcurrency: 4,
});
